zh:
  guide:
    - title: 品牌
      name: Guide
      items:
        - title: 色彩
          name: Color
        - title: 字体
          name: Typography
  resource:
    - title: 资源
      name: Resource
      items:
        - title: 设计资源
          name: design
  components:
    - title: 综述
      name: Docs
      items:
        - title: 介绍
          name: Introduction
        - title: 安装
          name: Installation
        - title: 快速上手
          name: Quickstart
        - title: 国际化
          name: I18n
        - title: 更新日志
          name: Changelog
    - title: 组件
      name: Docs
      groups:
        - title: 基础组件
          items:
            - title: 按钮
              name: Button
            - title: 布局
              name: Layout
            - title: 标签
              name: Tag
            - title: 图标
              name: Icon
        - title: 表单组件
          items:
            - title: 多选框
              name: Checkbox
            - title: 输入框
              name: Input
            - title: 数字输入框
              name: InputNumber
            - title: 单选按钮
              name: Radio
            - title: 评分
              name: Rate
            - title: 选择器
              name: Select
            - title: 开关
              name: Switch
            - title: 滑动输入条
              name: Slider
            - title: 文本域
              name: Textarea
        - title: 视图组件
          items:
            - title: 警告提示
              name: Alert
            - title: 徽标
              name: Badge
            - title: 卡片
              name: Card
            - title: 折叠面板
              name: Collapse
            - title: 加载进度条
              name: LoadingBar
            - title: 模态框
              name: Modal
            - title: 全局提示
              name: Message
            - title: 通知提醒
              name: Notification
            - title: 弹出框
              name: Popover
            - title: 进度条
              name: Progress
            - title: 时间轴
              name: Timeline
            - title: 文字提示
              name: Tooltip
            - title: 表格
              name: Table
        - title: 导航组件
          items:
            - title: 面包屑
              name: Breadcrumb
            - title: 下拉菜单
              name: Dropdown
            - title: 导航菜单
              name: Menu
            - title: 分页
              name: Pagination
            - title: 步骤条
              name: Steps
            - title: 标签页
              name: Tabs
en:
  guide:
    - title: Brand
      name: Guide
      items:
        - title: Color
          name: Color
        - title: Typography
          name: Typography
  resource:
    - title: Resource
      name: Resource
      items:
        - title: Design
          name: design
  components:
    - title: Overview
      name: Docs
      items:
        - title: Introduction
          name: Introduction
        - title: Installation
          name: Installation
        - title: Quickstart
          name: Quickstart
        - title: Internationalization
          name: i18n
        - title: Change Log
          name: Changelog
    - title: Components
      name: Docs
      groups:
        - title: Base
          items:
            - title: Button
              name: Button
            - title: Layout
              name: Layout
            - title: Tag
              name: Tag
            - title: Icon
              name: Icon
        - title: Form
          items:
            - title: Checkbox
              name: Checkbox
            - title: Input
              name: Input
            - title: InputNumber
              name: InputNumber
            - title: Radio
              name: Radio
            - title: Rate
              name: Rate
            - title: Select
              name: Select
            - title: Switch
              name: Switch
            - title: Slider
              name: Slider
            - title: Textarea
              name: Textarea
        - title: View
          items:
            - title: Alert
              name: Alert
            - title: Badge
              name: Badge
            - title: Card
              name: Card
            - title: Collapse
              name: Collapse
            - title: LoadingBar
              name: LoadingBar
            - title: Modal
              name: Modal
            - title: Message
              name: Message
            - title: Notification
              name: Notification
            - title: Popover
              name: Popover
            - title: Progress
              name: Progress
            - title: Timeline
              name: Timeline
            - title: Tooltip
              name: Tooltip
            - title: Table
              name: Table
        - title: Navigation
          items:
            - title: Breadcrumb
              name: Breadcrumb
            - title: Dropdown
              name: Dropdown
            - title: Menu
              name: Menu
            - title: Pagination
              name: Pagination
            - title: Steps
              name: Steps
            - title: Tabs
              name: Tabs
